AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Retire Strong API Gateway

Globals:
  Function:
    Runtime: nodejs20.x
    Timeout: 30
    MemorySize: 256
    Environment:
      Variables:
        NODE_ENV: development

Resources:
  HealthFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: dist/handlers/health.handler
      CodeUri: .
      Events:
        Health:
          Type: Api
          Properties:
            Path: /health
            Method: get

Outputs:
  ApiUrl:
    Description: API Gateway endpoint URL
    Value: !Sub 'https://${ServerlessHttpApi}.execute-api.${AWS::Region}.amazonaws.com'

