AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Retire Strong API Gateway

Globals:
  Function:
    Runtime: nodejs20.x
    Timeout: 30
    MemorySize: 256
    Environment:
      Variables:
        NODE_ENV: development

Resources:
  HealthFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: dist/handlers/health.handler
      CodeUri: .
      Events:
        Health:
          Type: Api
          Properties:
            Path: /health
            Method: get

  SignupFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: dist/handlers/auth/signup.handler
      CodeUri: .
      Environment:
        Variables:
          COGNITO_USER_POOL_ID: !Ref UserPool
          COGNITO_CLIENT_ID: !Ref UserPoolClient
          DYNAMO_TABLE_USERS: !Ref UsersTable
      Events:
        Signup:
          Type: Api
          Properties:
            Path: /auth/signup
            Method: post

  LoginFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: dist/handlers/auth/login.handler
      CodeUri: .
      Environment:
        Variables:
          COGNITO_USER_POOL_ID: !Ref UserPool
          COGNITO_CLIENT_ID: !Ref UserPoolClient
          DYNAMO_TABLE_USERS: !Ref UsersTable
      Events:
        Login:
          Type: Api
          Properties:
            Path: /auth/login
            Method: post

  OnboardingFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: dist/handlers/users/onboarding.handler
      CodeUri: .
      Environment:
        Variables:
          DYNAMO_TABLE_USERS: !Ref UsersTable
      Events:
        Onboarding:
          Type: Api
          Properties:
            Path: /users/onboarding
            Method: post

Outputs:
  ApiUrl:
    Description: API Gateway endpoint URL
    Value: !Sub 'https://${ServerlessHttpApi}.execute-api.${AWS::Region}.amazonaws.com'

